"""GENERATED by frontend/scripts/generate_identity.py from
frontend/src/styles/global.css — do not edit by hand. The site's
colour tokens, so the certificate (032) renders in the site's palette
and cannot drift from it (pinned by test_certificates.py).
"""

PALETTE = {
    "bg": "#f7f8fa",
    "surface": "#ffffff",
    "text": "#1a2233",
    "text-muted": "#5a6478",
    "border": "#d8dde6",
    "accent": "#1f4e8c",
    "accent-contrast": "#ffffff",
    "success": "#1e7a3c",
    "success-bg": "#e6f4ea",
    "error": "#a8322b",
    "error-bg": "#faeae9",
    "warning": "#8a6116",
    "warning-bg": "#fdf4dc",
}
