"""GENERATED by frontend/scripts/sync_brand.py from
frontend/src/styles/global.css — do not edit by hand. The site's
colour tokens, so the certificate renders in the site's palette and
cannot drift from it (sync_brand.py --check refuses a stale copy).
"""

PALETTE = {
    "bg": "#f5f7fb",
    "surface": "#ffffff",
    "text": "#14213d",
    "text-muted": "#51607a",
    "border": "#d5dcea",
    "brand-blue": "#006afc",
    "brand-navy": "#012c6b",
    "brand-teal": "#01b6af",
    "accent": "#0066f4",
    "accent-contrast": "#ffffff",
    "success": "#1e7a3c",
    "success-bg": "#e6f4ea",
    "error": "#a8322b",
    "error-bg": "#faeae9",
    "warning": "#8a6116",
    "warning-bg": "#fdf4dc",
}
