"""create attempts and attempt answers

Feature 007: qualified assessment attempts (6.01.2), in preview form.
CHECK constraints verified by hand against the model: status in
open/passed/failed, and preview_id set iff is_preview. The partial unique
index allows only one open attempt per (course, preview identity).
enrollment_id is a plain nullable integer; 010 adds its FK.

Revision ID: abaea95dc1b0
Revises: cf396feae240
Create Date: 2026-08-27 11:21:29.513411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abaea95dc1b0'
down_revision: Union[str, None] = 'cf396feae240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=True),
    sa.Column('preview_id', sa.String(), nullable=True),
    sa.Column('is_preview', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('passing_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('package_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("status IN ('open', 'passed', 'failed')", name='ck_attempts_status'),
    sa.CheckConstraint('is_preview = (preview_id IS NOT NULL)', name='ck_attempts_preview_id_iff_preview'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_course_id'), 'attempts', ['course_id'], unique=False)
    op.create_index('uq_attempts_one_open_per_preview', 'attempts', ['course_id', 'preview_id'], unique=True, postgresql_where=sa.text("status = 'open'"))
    op.create_table('attempt_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('choice_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['choice_id'], ['choices.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_attempt_answers_question')
    )
    op.create_index(op.f('ix_attempt_answers_attempt_id'), 'attempt_answers', ['attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempt_answers_attempt_id'), table_name='attempt_answers')
    op.drop_table('attempt_answers')
    op.drop_index('uq_attempts_one_open_per_preview', table_name='attempts', postgresql_where=sa.text("status = 'open'"))
    op.drop_index(op.f('ix_attempts_course_id'), table_name='attempts')
    op.drop_table('attempts')
    # ### end Alembic commands ###
