"""enrollment source renewal

Revision ID: c2d8e5f1a028
Revises: b7e3f9c2a815
Create Date: 2026-09-12 14:00:00.000000

028: `enrollments.source` gains 'renewal' — the no-charge enrollment a
participant who purchased a course and did not complete it may start
after the year runs out (9.02.2(3): a new enrollment with its own
expiration date, never an extension). CHECK constraints are not
autogenerated; this is written by hand. No other schema change: the
renewal is derived from the paid payment and the expired enrollment,
with no key to either.
"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c2d8e5f1a028'
down_revision: Union[str, None] = 'b7e3f9c2a815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_constraint('ck_enrollments_source', 'enrollments', type_='check')
    op.create_check_constraint(
        'ck_enrollments_source',
        'enrollments',
        "source IN ('admin', 'purchase', 'renewal')",
    )


def downgrade() -> None:
    op.drop_constraint('ck_enrollments_source', 'enrollments', type_='check')
    op.create_check_constraint(
        'ck_enrollments_source',
        'enrollments',
        "source IN ('admin', 'purchase')",
    )
