"""create questions and choices

Normalizes each stored package's questions.json into the new tables, with a
one-time backfill for packages ingested before this revision (from here on,
`packages.ingest` writes the rows itself in the ingest transaction). The
CHECK constraints are declared on the model and verified here by hand:
kind in review/assessment, and after_block set iff review.

Revision ID: cf396feae240
Revises: df4aae4f2bba
Create Date: 2026-08-27 10:39:50.008226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf396feae240'
down_revision: Union[str, None] = 'df4aae4f2bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('question_key', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('after_block', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('objective_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("(kind = 'review') = (after_block IS NOT NULL)", name='ck_questions_after_block_iff_review'),
    sa.CheckConstraint("kind IN ('review', 'assessment')", name='ck_questions_kind'),
    sa.ForeignKeyConstraint(['package_id'], ['lesson_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'question_key', name='uq_questions_package_id_question_key')
    )
    op.create_index(op.f('ix_questions_package_id'), 'questions', ['package_id'], unique=False)
    op.create_table('choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('choice_key', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'choice_key', name='uq_choices_question_id_choice_key')
    )
    op.create_index(op.f('ix_choices_question_id'), 'choices', ['question_id'], unique=False)
    # ### end Alembic commands ###

    # One-time backfill: packages ingested before this revision hold their
    # questions only as JSON. Same normalization `services.questions` does at
    # ingest, inlined so the migration does not import application code.
    bind = op.get_bind()
    questions_table = sa.table(
        "questions",
        sa.column("id", sa.Integer),
        sa.column("package_id", sa.Integer),
        sa.column("question_key", sa.String),
        sa.column("kind", sa.String),
        sa.column("after_block", sa.Integer),
        sa.column("position", sa.Integer),
        sa.column("stem", sa.Text),
        sa.column("feedback", sa.Text),
        sa.column("objective_keys", postgresql.JSONB),
    )
    choices_table = sa.table(
        "choices",
        sa.column("question_id", sa.Integer),
        sa.column("choice_key", sa.String),
        sa.column("text", sa.Text),
        sa.column("is_correct", sa.Boolean),
        sa.column("position", sa.Integer),
    )
    packages = bind.execute(
        sa.text("SELECT id, questions FROM lesson_packages ORDER BY id")
    ).fetchall()
    for package_id, questions in packages:
        for position, q in enumerate(questions, start=1):
            question_id = bind.execute(
                questions_table.insert()
                .values(
                    package_id=package_id,
                    question_key=q["id"],
                    kind=q["kind"],
                    after_block=q.get("after_block"),
                    position=position,
                    stem=q["stem"],
                    feedback=q["feedback"],
                    objective_keys=q["objective_ids"],
                )
                .returning(questions_table.c.id)
            ).scalar_one()
            for choice_position, c in enumerate(q["choices"], start=1):
                bind.execute(
                    choices_table.insert().values(
                        question_id=question_id,
                        choice_key=c["id"],
                        text=c["text"],
                        is_correct=c["id"] == q["correct"],
                        position=choice_position,
                    )
                )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_choices_question_id'), table_name='choices')
    op.drop_table('choices')
    op.drop_index(op.f('ix_questions_package_id'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
