"""create sponsor profile

Revision ID: d287428522f0
Revises: d770a4d597c5
Create Date: 2026-08-27 03:39:55.119192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd287428522f0'
down_revision: Union[str, None] = 'd770a4d597c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsor_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), server_default='', nullable=False),
    sa.Column('legal_name', sa.String(), server_default='', nullable=False),
    sa.Column('registry_status', sa.String(), server_default='not_registered', nullable=False),
    sa.Column('national_registry_id', sa.String(), server_default='', nullable=False),
    sa.Column('website', sa.String(), server_default='', nullable=False),
    sa.Column('contact_email', sa.String(), server_default='', nullable=False),
    sa.Column('contact_phone', sa.String(), server_default='', nullable=False),
    sa.Column('address', sa.String(), server_default='', nullable=False),
    sa.Column('other_certificate_statements', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("registry_status = 'registered' OR national_registry_id = ''", name='ck_sponsor_profile_registry_id_requires_registered'),
    sa.CheckConstraint("registry_status IN ('not_registered', 'registered')", name='ck_sponsor_profile_registry_status'),
    sa.CheckConstraint('id = 1', name='ck_sponsor_profile_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsor_state_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state')
    )
    # ### end Alembic commands ###

    # The singleton row exists from the moment the table does, so the
    # application never has to handle "no profile yet". Column defaults
    # fill in the blanks.
    op.execute("INSERT INTO sponsor_profile (id) VALUES (1)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sponsor_state_registrations')
    op.drop_table('sponsor_profile')
    # ### end Alembic commands ###
