"""subscriptions

Revision ID: d4b8e2a7c029
Revises: c2d8e5f1a028
Create Date: 2026-09-12 16:00:00.000000

029: the annual subscription. `subscriptions` and `subscription_invoices`
are financial records (never deleted, outliving RETENTION_YEARS) holding
what Stripe Billing last reported; `accounts.stripe_customer_id` is the
one durable Stripe Customer per account (set once, guests from 018 not
backfilled); `payments.credited_to_subscription_id` marks a course
payment whose amount was applied as credit on a subscription's first
invoice, so it is never credited twice; `enrollments.source` gains
'subscription'. CHECK constraints are not autogenerated and are written
by hand here, as 028 did.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd4b8e2a7c029'
down_revision: Union[str, None] = 'c2d8e5f1a028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

SUBSCRIPTION_STATUSES = (
    "'incomplete', 'incomplete_expired', 'trialing', 'active', "
    "'past_due', 'canceled', 'unpaid', 'paused'"
)
INVOICE_STATUSES = "'paid', 'open', 'void', 'uncollectible', 'refunded'"


def upgrade() -> None:
    op.add_column(
        'accounts',
        sa.Column('stripe_customer_id', sa.String(), nullable=True),
    )
    op.create_unique_constraint(
        'uq_accounts_stripe_customer_id', 'accounts', ['stripe_customer_id']
    )

    op.create_table(
        'subscriptions',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column(
            'account_id',
            sa.Integer(),
            sa.ForeignKey('accounts.id', ondelete='RESTRICT'),
            nullable=False,
        ),
        sa.Column('stripe_subscription_id', sa.String(), nullable=True),
        sa.Column('stripe_checkout_session_id', sa.String(), nullable=True),
        sa.Column('checkout_url', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column(
            'current_period_start', sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            'current_period_end', sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            'cancel_at_period_end',
            sa.Boolean(),
            nullable=False,
            server_default='false',
        ),
        sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'credit_applied_cents',
            sa.Integer(),
            nullable=False,
            server_default='0',
        ),
        sa.Column('livemode', sa.Boolean(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text('now()'),
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text('now()'),
        ),
        sa.UniqueConstraint(
            'stripe_subscription_id', name='uq_subscriptions_stripe_subscription_id'
        ),
        sa.UniqueConstraint(
            'stripe_checkout_session_id',
            name='uq_subscriptions_stripe_checkout_session_id',
        ),
        sa.CheckConstraint(
            f'status IN ({SUBSCRIPTION_STATUSES})', name='ck_subscriptions_status'
        ),
        sa.CheckConstraint(
            'credit_applied_cents >= 0',
            name='ck_subscriptions_credit_non_negative',
        ),
    )

    op.create_table(
        'subscription_invoices',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column(
            'subscription_id',
            sa.Integer(),
            sa.ForeignKey('subscriptions.id', ondelete='RESTRICT'),
            nullable=False,
        ),
        sa.Column('stripe_invoice_id', sa.String(), nullable=False),
        sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
        sa.Column('amount_paid_cents', sa.Integer(), nullable=False),
        sa.Column('currency', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
        sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
        sa.Column('livemode', sa.Boolean(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text('now()'),
        ),
        sa.UniqueConstraint(
            'stripe_invoice_id', name='uq_subscription_invoices_stripe_invoice_id'
        ),
        sa.CheckConstraint(
            f'status IN ({INVOICE_STATUSES})',
            name='ck_subscription_invoices_status',
        ),
        sa.CheckConstraint(
            'amount_paid_cents >= 0',
            name='ck_subscription_invoices_amount_non_negative',
        ),
    )

    op.add_column(
        'payments',
        sa.Column(
            'credited_to_subscription_id',
            sa.Integer(),
            sa.ForeignKey(
                'subscriptions.id',
                ondelete='RESTRICT',
                name='fk_payments_credited_to_subscription_id',
            ),
            nullable=True,
        ),
    )

    op.drop_constraint('ck_enrollments_source', 'enrollments', type_='check')
    op.create_check_constraint(
        'ck_enrollments_source',
        'enrollments',
        "source IN ('admin', 'purchase', 'renewal', 'subscription')",
    )


def downgrade() -> None:
    op.drop_constraint('ck_enrollments_source', 'enrollments', type_='check')
    op.create_check_constraint(
        'ck_enrollments_source',
        'enrollments',
        "source IN ('admin', 'purchase', 'renewal')",
    )
    op.drop_constraint(
        'fk_payments_credited_to_subscription_id', 'payments', type_='foreignkey'
    )
    op.drop_column('payments', 'credited_to_subscription_id')
    op.drop_table('subscription_invoices')
    op.drop_table('subscriptions')
    op.drop_constraint('uq_accounts_stripe_customer_id', 'accounts', type_='unique')
    op.drop_column('accounts', 'stripe_customer_id')
