"""create lesson_packages

Revision ID: d770a4d597c5
Revises: 
Create Date: 2026-08-27 02:10:05.026933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd770a4d597c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('duration_source', sa.String(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('narration_blocks', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('av_is_additional_learning', sa.Boolean(), nullable=False),
    sa.Column('field_of_study', sa.String(), nullable=False),
    sa.Column('knowledge_level', sa.String(), nullable=False),
    sa.Column('prerequisites', sa.Text(), nullable=False),
    sa.Column('advance_preparation', sa.Text(), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('video_key', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("duration_source = 'measured'", name='ck_lesson_packages_duration_source_measured'),
    sa.CheckConstraint("field_of_study IN ('Accounting', 'Accounting (Governmental)', 'Auditing', 'Auditing (Governmental)', 'Business Law', 'Economics', 'Finance', 'Information Technology', 'Management Services', 'Regulatory Ethics', 'Specialized Knowledge', 'Statistics', 'Taxes', 'Behavioral Ethics', 'Business Management & Organization', 'Communications and Marketing', 'Computer Software & Applications', 'Personal Development', 'Personnel/Human Resources', 'Production')", name='ck_lesson_packages_field_of_study'),
    sa.CheckConstraint("knowledge_level IN ('Basic', 'Intermediate', 'Advanced', 'Update', 'Overview')", name='ck_lesson_packages_knowledge_level'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash'),
    sa.UniqueConstraint('lesson_id', 'version', name='uq_lesson_packages_lesson_id_version')
    )
    op.create_index(op.f('ix_lesson_packages_lesson_id'), 'lesson_packages', ['lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_packages_lesson_id'), table_name='lesson_packages')
    op.drop_table('lesson_packages')
    # ### end Alembic commands ###
