"""add credit measurement

Revision ID: df4aae4f2bba
Revises: d014c39c688d
Create Date: 2026-08-27 05:03:35.685873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df4aae4f2bba'
down_revision: Union[str, None] = 'd014c39c688d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('credit_award', sa.Numeric(precision=4, scale=1), nullable=True))
    op.add_column('courses', sa.Column('credit_raw_minutes', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('courses', sa.Column('credit_word_count', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('credit_av_seconds', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('credit_question_count', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('credit_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('courses', sa.Column('credit_formula_version', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('credit_computed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'credit_computed_at')
    op.drop_column('courses', 'credit_formula_version')
    op.drop_column('courses', 'credit_breakdown')
    op.drop_column('courses', 'credit_question_count')
    op.drop_column('courses', 'credit_av_seconds')
    op.drop_column('courses', 'credit_word_count')
    op.drop_column('courses', 'credit_raw_minutes')
    op.drop_column('courses', 'credit_award')
    # ### end Alembic commands ###
