"""development and review chain

Revision ID: eadb4ff2d315
Revises: abaea95dc1b0
Create Date: 2026-08-27 11:53:17.202397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eadb4ff2d315'
down_revision: Union[str, None] = 'abaea95dc1b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_matter_experts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('credentials', sa.String(), server_default='', nullable=False),
    sa.Column('credential_type', sa.String(), nullable=False),
    sa.Column('license_jurisdiction', sa.String(), server_default='', nullable=False),
    sa.Column('license_number', sa.String(), server_default='', nullable=False),
    sa.Column('license_status', sa.String(), server_default='unknown', nullable=False),
    sa.Column('email', sa.String(), server_default='', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("credential_type IN ('cpa', 'tax_attorney', 'enrolled_agent', 'other')", name='ck_smes_credential_type'),
    sa.CheckConstraint("license_status IN ('active', 'inactive', 'unknown')", name='ck_smes_license_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.Date(), nullable=False),
    sa.Column('content_updated_at_reviewed', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('impractical_basis', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('approved', 'changes_requested')", name='ck_course_reviews_decision'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['subject_matter_experts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('courses', sa.Column('developer_id', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('developer_used_technology', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('courses', sa.Column('review_cycle', sa.String(), server_default='biennial', nullable=False))
    op.add_column('courses', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('courses', sa.Column('unpublished_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key('fk_courses_developer_id', 'courses', 'subject_matter_experts', ['developer_id'], ['id'], ondelete='RESTRICT')
    # Added by hand: autogenerate does not write CHECK constraints for
    # added columns.
    op.create_check_constraint(
        'ck_courses_review_cycle', 'courses', "review_cycle IN ('annual', 'biennial')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_courses_review_cycle', 'courses', type_='check')
    op.drop_constraint('fk_courses_developer_id', 'courses', type_='foreignkey')
    op.drop_column('courses', 'unpublished_at')
    op.drop_column('courses', 'published_at')
    op.drop_column('courses', 'review_cycle')
    op.drop_column('courses', 'developer_used_technology')
    op.drop_column('courses', 'developer_id')
    op.drop_table('course_reviews')
    op.drop_table('subject_matter_experts')
    # ### end Alembic commands ###
